export enum Etape {
  EN_ATTENDE = 'EN_ATTENDE',

  NON_RETENU = 'NON_RETENU',

  RETENU = 'RETENU',

  ANNULE = 'ANNULE',

  CONCEPTION = 'CONCEPTION',

  PRESENTATION_MAQUETAGE = 'PRESENTATION_MAQUETAGE',

  DEVELOPPEMENT = 'DEVELOPPEMENT',

  RECETTE = 'RECETTE',

  FORMATION = 'FORMATION',

  EN_SUIVI = 'EN_SUIVI',

  MISE_EN_SERVICE = 'MISE_EN_SERVICE',

  MISE_EN_EXPLOITATION = 'MISE_EN_EXPLOITATION',

  TERMINER = 'TERMINER',
}
